[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "2.7.2", package = "codspeed-criterion-compat" }


[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
voracious_radix_sort = "=1.2.0"
